
import productImage from "../assets/product.png";
export const products = [
    {
        id: 1,
        title: "Hệ Hy-Brid 5 kWp 1 pha - Lưu trữ 5.12 kWh Cao Cấp",
        image: productImage,
        save: "5.000.000 đ",
        price: "49.900.000 đ",
        pv: "50 kW",
        inverter: "50 kW",
        battery: "Lưu trữ Dyness",
        production: "350-450 kWh/tháng",
        roi: "3 năm 6 tháng",
        area: "21 m2",
    },
    {
        id: 2,
        title: "Hệ Hy-Brid 5 kWp 1 pha - Lưu trữ 5.12 kWh Cao Cấp",
        image: productImage,
        save: "5.000.000 đ",
        price: "49.900.000 đ",
        pv: "50 kW",
        inverter: "50 kW",
        battery: "Lưu trữ Dyness",
        production: "350-450 kWh/tháng",
        roi: "3 năm 6 tháng",
        area: "21 m2",
    },
     {
        id: 3,
        title: "Hệ Hy-Brid 5 kWp 1 pha - Lưu trữ 5.12 kWh Cao Cấp",
        image: productImage,
        save: "Tiết kiệm tiền điện mỗi tháng: 5.000.000 đ",
        price: "49.900.000 đ",
        pv: "50 kW",
        inverter: "50 kW",
        battery: "Lưu trữ Dyness",
        production: "350-450 kWh/tháng",
        roi: "3 năm 6 tháng",
        area: "21 m2",
    },
    {
        id: 4,
        title: "Hệ Hy-Brid 5 kWp 1 pha - Lưu trữ 5.12 kWh Cao Cấp",
        image: productImage,
        save: "Tiết kiệm tiền điện mỗi tháng: 5.000.000 đ",
        price: "49.900.000 đ",
        pv: "50 kW",
        inverter: "50 kW",
        battery: "Lưu trữ Dyness",
        production: "350-450 kWh/tháng",
        roi: "3 năm 6 tháng",
        area: "21 m2",
    },
     {
        id: 5,
        title: "Hệ Hy-Brid 5 kWp 1 pha - Lưu trữ 5.12 kWh Cao Cấp",
        image: productImage,
        save: "Tiết kiệm tiền điện mỗi tháng: 5.000.000 đ",
        price: "49.900.000 đ",
        pv: "50 kW",
        inverter: "50 kW",
        battery: "Lưu trữ Dyness",
        production: "350-450 kWh/tháng",
        roi: "3 năm 6 tháng",
        area: "21 m2",
    },
    {
        id: 6,
        title: "Hệ Hy-Brid 5 kWp 1 pha - Lưu trữ 5.12 kWh Cao Cấp",
        image: productImage,
        save: "Tiết kiệm tiền điện mỗi tháng: 5.000.000 đ",
        price: "49.900.000 đ",
        pv: "50 kW",
        inverter: "50 kW",
        battery: "Lưu trữ Dyness",
        production: "350-450 kWh/tháng",
        roi: "3 năm 6 tháng",
        area: "21 m2",
    },
     {
        id: 7,
        title: "Hệ Hy-Brid 5 kWp 1 pha - Lưu trữ 5.12 kWh Cao Cấp",
        image: productImage,
        save: "Tiết kiệm tiền điện mỗi tháng: 5.000.000 đ",
        price: "49.900.000 đ",
        pv: "50 kW",
        inverter: "50 kW",
        battery: "Lưu trữ Dyness",
        production: "350-450 kWh/tháng",
        roi: "3 năm 6 tháng",
        area: "21 m2",
    },
    {
        id: 8,
        title: "Hệ Hy-Brid 5 kWp 1 pha - Lưu trữ 5.12 kWh Cao Cấp",
        image: productImage,
        save: "Tiết kiệm tiền điện mỗi tháng: 5.000.000 đ",
        price: "49.900.000 đ",
        pv: "50 kW",
        inverter: "50 kW",
        battery: "Lưu trữ Dyness",
        production: "350-450 kWh/tháng",
        roi: "3 năm 6 tháng",
        area: "21 m2",
    },
];
